version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./backend/rails/tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend/
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./backend/rails:/usr/src/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend/
    command: yarn run dev
    volumes:
      - ./frontend/nuxt:/usr/src/app
    ports:
      - "3000:3000"
